#!/usr/bin/env node
/**
 * AnyMentor Setup Wizard
 * Single command: node setup.js
 * Opens browser automatically — no terminal input needed.
 */

const http = require('http');
const fs   = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execSync, spawn } = require('child_process');

const PORT     = 3099;
const ROOT     = __dirname;
const ENV_FILE = path.join(ROOT, 'backend', '.env');

let setupLog  = [];
let setupDone = false;
let setupErr  = null;
let setupRunning = false;

function gen(bytes = 48) { return crypto.randomBytes(bytes).toString('hex'); }

function openBrowser(url) {
  const cmd = process.platform === 'win32' ? `start ${url}`
    : process.platform === 'darwin' ? `open ${url}` : `xdg-open ${url} 2>/dev/null || true`;
  try { execSync(cmd); } catch {}
}

function log(msg) {
  setupLog.push({ t: new Date().toISOString(), msg });
  process.stdout.write(msg + '\n');
}

function runCmd(cmd, opts = {}) {
  return new Promise((resolve, reject) => {
    log(`$ ${cmd}`);
    const child = spawn('sh', ['-c', cmd], { cwd: ROOT, env: { ...process.env, FORCE_COLOR: '0' }, ...opts });
    child.stdout?.on('data', d => log(d.toString().trim()));
    child.stderr?.on('data', d => log(d.toString().trim()));
    child.on('close', code => code === 0 ? resolve() : reject(new Error(`Command failed (exit ${code}): ${cmd}`)));
  });
}

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

async function runSetup(cfg) {
  setupRunning = true;
  setupLog = [];
  setupDone = false;
  setupErr = null;

  try {
    // ── Step 1: Write .env ──────────────────────────────────────
    log('📝 Writing backend/.env ...');
    const dbPass = cfg.dbPassword || 'anymentor123';
    const dbName = cfg.dbName    || 'anymentor';
    const dbUser = cfg.dbUser    || 'anymentor';

    const env = `# Generated by AnyMentor Setup Wizard
NODE_ENV=development
PORT=3000

# Database
DATABASE_URL=postgresql://${dbUser}:${dbPass}@postgres:5432/${dbName}
POSTGRES_USER=${dbUser}
POSTGRES_PASSWORD=${dbPass}
POSTGRES_DB=${dbName}

# JWT
JWT_ACCESS_SECRET=${gen()}
JWT_REFRESH_SECRET=${gen()}
JWT_ACCESS_EXPIRES=15m
JWT_REFRESH_EXPIRES=7d

# Owner Account
OWNER_EMAIL=${cfg.ownerEmail}
OWNER_PASSWORD=${cfg.ownerPassword}

# First Company
COMPANY_NAME=${cfg.companyName}
COMPANY_SLUG=${cfg.companySlug}
ADMIN_EMAIL=${cfg.adminEmail}
ADMIN_PASSWORD=${cfg.adminPassword}

# Razorpay (Indian Payments)
RAZORPAY_KEY_ID=${cfg.razorpayKeyId || ''}
RAZORPAY_KEY_SECRET=${cfg.razorpaySecret || ''}
RAZORPAY_WEBHOOK_SECRET=${cfg.razorpayWebhook || ''}

# PhonePe
PHONEPE_MERCHANT_ID=${cfg.phonepeId || ''}
PHONEPE_SALT_KEY=${cfg.phonepeSalt || ''}
PHONEPE_SALT_INDEX=${cfg.phonepeSaltIndex || '1'}
PHONEPE_ENV=${cfg.phonepeEnv || 'SANDBOX'}

# Stripe (International)
STRIPE_SECRET_KEY=${cfg.stripeSecret || ''}
STRIPE_WEBHOOK_SECRET=${cfg.stripeWebhook || ''}
STRIPE_PUBLISHABLE_KEY=${cfg.stripePublic || ''}

# UPI
UPI_VPA=${cfg.upiVpa || ''}
UPI_NAME=${cfg.companyName || 'AnyMentor'}

# Email (SMTP)
SMTP_HOST=${cfg.smtpHost || 'smtp.gmail.com'}
SMTP_PORT=${cfg.smtpPort || '587'}
SMTP_USER=${cfg.smtpUser || ''}
SMTP_PASS=${cfg.smtpPass || ''}
SMTP_FROM=${cfg.smtpFrom || cfg.ownerEmail}

# File Upload
UPLOAD_DIR=uploads
MAX_FILE_SIZE_MB=10

# Redis
REDIS_URL=redis://redis:6379

# Security
BCRYPT_ROUNDS=12
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX=100

# Frontend
FRONTEND_URL=http://localhost:5173
ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000
`;
    fs.writeFileSync(ENV_FILE, env, 'utf-8');
    log('✅ .env written');

    // Also update docker-compose postgres env vars
    log('📦 Starting Docker containers ...');
    await runCmd('docker-compose up -d --build');

    log('⏳ Waiting for PostgreSQL to be ready ...');
    for (let i = 0; i < 30; i++) {
      try {
        execSync('docker-compose exec -T postgres pg_isready -U anymentor', { stdio: 'ignore', cwd: ROOT });
        log('✅ PostgreSQL is ready');
        break;
      } catch {
        await sleep(2000);
        log(`   Still waiting... (${i + 1}/30)`);
      }
    }

    log('🗃️  Running database migrations ...');
    await runCmd('docker-compose exec -T backend npx prisma migrate deploy');

    log('🌱 Seeding database ...');
    await runCmd('docker-compose exec -T backend node prisma/seed.js');

    log('');
    log('🎉 Setup complete!');
    log(`   Frontend  → http://localhost:5173`);
    log(`   API Docs  → http://localhost:3000/api/docs`);
    log(`   Owner     → ${cfg.ownerEmail}`);
    log(`   Admin     → ${cfg.adminEmail}`);

    setupDone = true;
  } catch (err) {
    setupErr = err.message;
    log('❌ Setup failed: ' + err.message);
  } finally {
    setupRunning = false;
  }
}

// ── HTML ────────────────────────────────────────────────────────
const HTML = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AnyMentor Setup Wizard</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:'Segoe UI',system-ui,sans-serif;background:#f5f0e8;min-height:100vh;color:#1a3c6e}
.hero{background:linear-gradient(135deg,#1a3c6e 0%,#800020 100%);color:#fff;padding:2.5rem 1rem;text-align:center}
.hero h1{font-size:2.2rem;font-weight:800;letter-spacing:-0.5px}
.hero p{opacity:.85;margin-top:.5rem;font-size:1.05rem}
.badge{display:inline-block;background:#d4a017;color:#fff;padding:.25rem .75rem;border-radius:999px;font-size:.75rem;font-weight:700;margin-top:.75rem;letter-spacing:.5px}
.container{max-width:820px;margin:0 auto;padding:2rem 1rem 4rem}
.card{background:#fff;border-radius:1rem;padding:1.75rem;margin-bottom:1.5rem;box-shadow:0 2px 12px rgba(26,60,110,.08)}
.section-title{font-size:1rem;font-weight:700;color:#800020;text-transform:uppercase;letter-spacing:.5px;margin-bottom:1.25rem;padding-bottom:.5rem;border-bottom:2px solid #f5f0e8}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}
@media(max-width:600px){.grid{grid-template-columns:1fr}}
.field{display:flex;flex-direction:column;gap:.35rem}
label{font-size:.8rem;font-weight:600;color:#1a3c6e;text-transform:uppercase;letter-spacing:.3px}
label span{font-weight:400;color:#888;text-transform:none;letter-spacing:0}
input,select{padding:.65rem .9rem;border:1.5px solid #e2ddd5;border-radius:.6rem;font-size:.95rem;color:#1a3c6e;background:#fff;transition:border .2s}
input:focus,select:focus{outline:none;border-color:#1a3c6e;box-shadow:0 0 0 3px rgba(26,60,110,.1)}
input::placeholder{color:#bbb}
.auto-badge{font-size:.7rem;background:#f0f7ff;color:#1a3c6e;border:1px solid #c5d8f0;padding:.15rem .5rem;border-radius:.3rem;display:inline-block;margin-left:.4rem}
.optional{font-size:.7rem;background:#fef9ec;color:#b07d0a;border:1px solid #f0d98a;padding:.15rem .5rem;border-radius:.3rem;display:inline-block;margin-left:.4rem}
.hint{font-size:.75rem;color:#999;margin-top:.2rem}
.btn{width:100%;padding:1rem;background:linear-gradient(135deg,#1a3c6e,#800020);color:#fff;border:none;border-radius:.75rem;font-size:1.1rem;font-weight:700;cursor:pointer;transition:opacity .2s;margin-top:.5rem}
.btn:hover{opacity:.9}
.btn:disabled{opacity:.5;cursor:not-allowed}

/* Progress */
#progress{display:none}
#progress.show{display:block}
.progress-bar-wrap{background:#e2ddd5;border-radius:999px;height:10px;margin:1rem 0;overflow:hidden}
.progress-bar{height:100%;background:linear-gradient(90deg,#1a3c6e,#d4a017);border-radius:999px;transition:width .4s;width:0%}
.log-box{background:#1a1a2e;color:#a8d8a8;font-family:'Courier New',monospace;font-size:.78rem;padding:1rem;border-radius:.75rem;height:260px;overflow-y:auto;line-height:1.7}
.log-box .err{color:#ff8a80}
.success-box{text-align:center;padding:2rem;background:linear-gradient(135deg,#1a3c6e,#800020);color:#fff;border-radius:1rem}
.success-box h2{font-size:1.8rem;margin-bottom:1rem}
.cred-box{display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin-top:1.25rem}
.cred{background:rgba(255,255,255,.15);border-radius:.75rem;padding:1rem;text-align:left}
.cred .k{font-size:.7rem;opacity:.7;text-transform:uppercase;letter-spacing:.5px;margin-bottom:.35rem}
.cred .v{font-size:.9rem;font-weight:600;word-break:break-all}
.link-btn{display:inline-block;margin-top:1rem;background:#d4a017;color:#fff;padding:.65rem 1.5rem;border-radius:.6rem;font-weight:700;text-decoration:none;font-size:.95rem}
@media(max-width:600px){.cred-box{grid-template-columns:1fr}}
</style>
</head>
<body>

<div class="hero">
  <h1>⚡ AnyMentor</h1>
  <p>Setup Wizard — Configure your platform in minutes</p>
  <div class="badge">SETUP v1.0</div>
</div>

<div class="container">

<form id="form">

  <!-- Platform Owner -->
  <div class="card">
    <div class="section-title">Platform Owner</div>
    <div class="grid">
      <div class="field">
        <label>Owner Email</label>
        <input type="email" name="ownerEmail" placeholder="owner@yourplatform.com" required>
      </div>
      <div class="field">
        <label>Owner Password</label>
        <input type="password" name="ownerPassword" placeholder="Min 8 chars" required minlength="8">
        <span class="hint">This is the super-admin account (full platform access)</span>
      </div>
    </div>
  </div>

  <!-- First Company -->
  <div class="card">
    <div class="section-title">First Company (Your Portal)</div>
    <div class="grid">
      <div class="field">
        <label>Company Name</label>
        <input type="text" name="companyName" placeholder="Acme Academy" required id="companyNameInput">
      </div>
      <div class="field">
        <label>Company Slug <span>(URL: /c/your-slug)</span></label>
        <input type="text" name="companySlug" placeholder="acme-academy" required id="companySlugInput" pattern="[a-z0-9-]+">
        <span class="hint">Only lowercase letters, numbers, hyphens</span>
      </div>
      <div class="field">
        <label>Admin Email</label>
        <input type="email" name="adminEmail" placeholder="admin@acme.com" required>
      </div>
      <div class="field">
        <label>Admin Password</label>
        <input type="password" name="adminPassword" placeholder="Min 8 chars" required minlength="8">
      </div>
    </div>
  </div>

  <!-- Database -->
  <div class="card">
    <div class="section-title">Database</div>
    <div class="grid">
      <div class="field">
        <label>DB Password</label>
        <input type="text" name="dbPassword" placeholder="anymentor123 (default)" value="anymentor123">
        <span class="hint">PostgreSQL password for the database user</span>
      </div>
      <div class="field">
        <label>DB Name</label>
        <input type="text" name="dbName" placeholder="anymentor" value="anymentor">
      </div>
    </div>
  </div>

  <!-- Indian Payments -->
  <div class="card">
    <div class="section-title">Indian Payments <span class="optional">OPTIONAL</span></div>
    <div class="grid">
      <div class="field">
        <label>Razorpay Key ID <span class="optional">optional</span></label>
        <input type="text" name="razorpayKeyId" placeholder="rzp_live_xxxxx">
      </div>
      <div class="field">
        <label>Razorpay Key Secret <span class="optional">optional</span></label>
        <input type="password" name="razorpaySecret" placeholder="your secret">
      </div>
      <div class="field">
        <label>PhonePe Merchant ID <span class="optional">optional</span></label>
        <input type="text" name="phonepeId" placeholder="PGTESTPAYUAT">
      </div>
      <div class="field">
        <label>PhonePe Salt Key <span class="optional">optional</span></label>
        <input type="password" name="phonepeSalt" placeholder="salt key">
      </div>
      <div class="field">
        <label>UPI VPA (ID) <span class="optional">optional</span></label>
        <input type="text" name="upiVpa" placeholder="yourbusiness@upi">
        <span class="hint">For UPI QR code payments</span>
      </div>
      <div class="field">
        <label>PhonePe Environment</label>
        <select name="phonepeEnv">
          <option value="SANDBOX">Sandbox (Testing)</option>
          <option value="PRODUCTION">Production</option>
        </select>
      </div>
    </div>
  </div>

  <!-- International -->
  <div class="card">
    <div class="section-title">International Payments (Stripe) <span class="optional">OPTIONAL</span></div>
    <div class="grid">
      <div class="field">
        <label>Stripe Secret Key <span class="optional">optional</span></label>
        <input type="password" name="stripeSecret" placeholder="sk_live_xxxxx">
      </div>
      <div class="field">
        <label>Stripe Publishable Key <span class="optional">optional</span></label>
        <input type="text" name="stripePublic" placeholder="pk_live_xxxxx">
      </div>
    </div>
  </div>

  <!-- Email -->
  <div class="card">
    <div class="section-title">Email (SMTP) <span class="optional">OPTIONAL</span></div>
    <div class="grid">
      <div class="field">
        <label>SMTP Host</label>
        <input type="text" name="smtpHost" placeholder="smtp.gmail.com">
      </div>
      <div class="field">
        <label>SMTP Port</label>
        <input type="text" name="smtpPort" placeholder="587">
      </div>
      <div class="field">
        <label>SMTP User</label>
        <input type="email" name="smtpUser" placeholder="noreply@yourcompany.com">
      </div>
      <div class="field">
        <label>SMTP Password / App Key</label>
        <input type="password" name="smtpPass" placeholder="app password">
      </div>
    </div>
    <p class="hint" style="margin-top:.75rem">Gmail: use App Password (not your main password). Leave blank to skip email features.</p>
  </div>

  <button type="submit" class="btn" id="submitBtn">🚀 Start Setup</button>
</form>

<!-- Progress Section -->
<div id="progress">
  <div class="card">
    <div class="section-title" id="progressTitle">Setting up...</div>
    <div class="progress-bar-wrap"><div class="progress-bar" id="progressBar"></div></div>
    <div class="log-box" id="logBox"></div>
  </div>
  <div id="successBox"></div>
</div>

</div>

<script>
// Auto-generate slug from company name
document.getElementById('companyNameInput').addEventListener('input', function() {
  const slug = this.value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  document.getElementById('companySlugInput').value = slug;
});

let pollInterval;
let startTime;
let savedCfg = {};

document.getElementById('form').addEventListener('submit', async function(e) {
  e.preventDefault();
  const fd = new FormData(this);
  const cfg = Object.fromEntries(fd.entries());
  savedCfg = cfg;

  document.getElementById('form').style.display = 'none';
  document.getElementById('progress').classList.add('show');
  document.getElementById('submitBtn').disabled = true;
  startTime = Date.now();

  // Send setup request
  fetch('/setup', {
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    body: JSON.stringify(cfg)
  }).catch(() => {});

  // Poll for status
  pollInterval = setInterval(pollStatus, 1500);
  pollStatus();
});

let lastLogCount = 0;
async function pollStatus() {
  try {
    const res = await fetch('/status');
    const data = await res.json();

    const logBox = document.getElementById('logBox');
    const newLogs = data.logs.slice(lastLogCount);
    newLogs.forEach(entry => {
      const div = document.createElement('div');
      div.textContent = '> ' + entry.msg;
      if (entry.msg.includes('❌') || entry.msg.includes('Error') || entry.msg.includes('failed')) {
        div.className = 'err';
      }
      logBox.appendChild(div);
    });
    lastLogCount = data.logs.length;
    logBox.scrollTop = logBox.scrollHeight;

    // Update progress bar
    const pct = Math.min(95, (Date.now() - startTime) / 1200);
    document.getElementById('progressBar').style.width = pct + '%';

    if (data.done) {
      clearInterval(pollInterval);
      document.getElementById('progressBar').style.width = '100%';
      document.getElementById('progressTitle').textContent = '✅ Setup Complete!';
      showSuccess();
    } else if (data.error) {
      clearInterval(pollInterval);
      document.getElementById('progressTitle').textContent = '❌ Setup Failed';
      document.getElementById('progressBar').style.background = '#ff5252';
    }
  } catch {}
}

function showSuccess() {
  document.getElementById('successBox').innerHTML = \`
    <div class="success-box">
      <h2>🎉 AnyMentor is Ready!</h2>
      <p>Your platform has been set up. Use these credentials to log in.</p>
      <div class="cred-box">
        <div class="cred"><div class="k">Frontend</div><div class="v">http://localhost:5173</div></div>
        <div class="cred"><div class="k">API Docs</div><div class="v">http://localhost:3000/api/docs</div></div>
        <div class="cred"><div class="k">Owner Login</div><div class="v">\${savedCfg.ownerEmail}</div></div>
        <div class="cred"><div class="k">Admin Login</div><div class="v">\${savedCfg.adminEmail}</div></div>
      </div>
      <a href="http://localhost:5173" class="link-btn" target="_blank">Open AnyMentor →</a>
    </div>
  \`;
}
</script>
</body>
</html>`;

// ── HTTP Server ─────────────────────────────────────────────────
const server = http.createServer((req, res) => {
  if (req.method === 'GET' && req.url === '/') {
    // If already setup, show status
    if (fs.existsSync(ENV_FILE)) {
      res.writeHead(200, { 'Content-Type': 'text/html' });
      res.end(HTML.replace(
        '<button type="submit" class="btn" id="submitBtn">🚀 Start Setup</button>',
        `<div style="background:#fff3cd;border:1px solid #ffc107;padding:1rem;border-radius:.6rem;margin-bottom:1rem;color:#856404">
          ⚠️ <strong>backend/.env already exists.</strong> Submitting will overwrite it. Or run again to reconfigure.
         </div>
         <button type="submit" class="btn" id="submitBtn">🔄 Reconfigure & Restart</button>`
      ));
      return;
    }
    res.writeHead(200, { 'Content-Type': 'text/html' });
    res.end(HTML);

  } else if (req.method === 'POST' && req.url === '/setup') {
    let body = '';
    req.on('data', d => body += d);
    req.on('end', () => {
      try {
        const cfg = JSON.parse(body);
        runSetup(cfg); // fire and forget — client polls /status
        res.writeHead(202, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ started: true }));
      } catch (e) {
        res.writeHead(400);
        res.end(JSON.stringify({ error: e.message }));
      }
    });

  } else if (req.method === 'GET' && req.url === '/status') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ logs: setupLog, done: setupDone, error: setupErr, running: setupRunning }));

  } else {
    res.writeHead(404);
    res.end('Not found');
  }
});

server.listen(PORT, '0.0.0.0', () => {
  const url = `http://localhost:${PORT}`;
  console.log('\n');
  console.log('╔══════════════════════════════════════════╗');
  console.log('║     🚀  AnyMentor Setup Wizard           ║');
  console.log('╠══════════════════════════════════════════╣');
  console.log(`║  Open in browser:  ${url}  ║`);
  console.log('╚══════════════════════════════════════════╝');
  console.log('\nSetup wizard is running. Press Ctrl+C after setup is done.\n');
  openBrowser(url);
});
